name: echo-action

on:
  #  schedule:
  #    - cron: '*/5 * * * *'
  workflow_dispatch:
  workflow_call:

jobs:
  my-job:
    name: echo-job
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Hello world"